[package]
name = "rust_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "7.0.0-rc1" # DashMap内部采用分片哈希表，减少锁竞争‌
rsa = "0.7"           # RSA 加密库
rand = "0.8"          # 随机数生成库
base64 = "0.13"       # 添加 base64 库的依赖
